### ISSUE TITLE
[Functional Component] Math Magician : Functional Component

### ISSUE THREAD

**Issue by roniy68** [roniy68/math-magician#5]
# ⚛️React Functional Component ⚛️ 

## Highlights ✅ 
✔️  Already built the calculator using Functional Component. 😄 

A React functional component is a type of component in React that is defined as a JavaScript function. 🎉

👨‍💻 It's a simple and concise way to create reusable UI components in React. Functional components can be created using the function keyword or using arrow functions. 🚀

💡 They take in props as input, which is an object of properties that are passed to the component when it is rendered. These props can be used to control the behavior and appearance of the component. 🌟

💪 Functional components can also make use of React's hooks, which allow them to manage local state, handle lifecycle events, and perform other actions within the component. 💥

👍 In general, functional components are considered to be easier to read and write than class components in React, and they are the recommended way to create components in modern versions of React. 🎓

## 💻 Code Explanation

👉 This code exports a React functional component called `Calculator` which represents a basic calculator UI. 

👉 The component initializes its state using the `useState` hook to create an object called `dataObj`. This object contains three properties that will be updated throughout the lifecycle of the component: `total`, `next`, and `operation`. 

👉 The `handleClick` function is defined within the component and is called each time a button is clicked. It takes an event object as its argument and uses the `calculate` function, which is imported from a `logic/calculate` module, to update the state of `dataObj` based on the text content of the button that was clicked.

👉 The component renders a `Display` component, which is another React functional component, and a collection of `NumberBtn` and `OperationBtn` components. These sub-components are passed properties such as `result`, `type`, `number`, and `operation` and will render accordingly. 

## 🧮 Functionality

✅ The `Calculator` component provides a basic calculator UI that allows users to perform mathematical calculations by clicking on buttons.

✅ The component uses React's state management and event handling capabilities to keep track of the user's input and display the result of their calculations.

## 🎨 Components

🔹 `Calculator`: The main component that renders the calculator UI and manages the state of `dataObj`.

🔹 `Display`: A sub-component that displays the current calculation result.

🔹 `NumberBtn`: A sub-component that represents a numeric button on the calculator.

🔹 `OperationBtn`: A sub-component that represents an operation button on the calculator.

## 🚀 Conclusion

👍 Overall, this code represents a well-structured and functional React component that provides a simple calculator UI. The use of state and sub-components demonstrates best practices for React development, and the `handleClick` function shows how to handle events in a clear and concise way.

**Comment by BertrandConxy** [comment]
Hi @roniy68, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- Good explanation 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by roniy68** [comment]
# Thanks @BertrandConxy 

![g](https://media.giphy.com/media/KB8C86UMgLDThpt4WT/giphy.gif)
